### ISSUE TITLE
Full release of code

### ISSUE THREAD

**Issue by Vincentqyw** [PRBonn/descriptor-dr#1]
Hi,

Thank you for the amazing project.  

I am currently working on local feature matching, your algorithm introduced in paper fit me well.

I just wondering when will the full release the code.

Thx again.

**Comment by Vincentqyw** [comment]
And another question: have you tried using your proposed descriptor dimension deduction method on SuperPoint or other modern CNN descriptors?

**Comment by donghao51** [comment]
Hello, thanks for your interest in our work. We plan to release the code in late March or early April. 
We didn't try on SuperPoint but the HardNet tested in our paper is also one of the SOTA CNN descriptors.

**Comment by Vincentqyw** [comment]
Got it!
